version: "2.1"
services:
  shell:
    image: "${IMAGE:-eeacms/plone}"
    depends_on:
      - memcached
      - postfix
      - zeo
      - postgres
    environment:
      ZOPE_MODE: "${ZOPE_MODE:-zeo_client}"
      TZ: "Europe/Copenhagen"
    tty: true
    stdin_open: true
    command: cat
    ports:
    - 3080:8080

  plone:
    image: "${IMAGE:-eeacms/plone}"
    ports:
    - "8080:8080"
    depends_on:
      - memcached
      - postfix
      - zeo
      - postgres
    environment:
      ZOPE_MODE: "${ZOPE_MODE:-zeo_client}"
      TZ: "Europe/Copenhagen"

  # Upgrade all GenericSetup profies once each time services are started.
  plonesite:
    image: "${IMAGE:-eeacms/plone}"
    depends_on:
      - memcached
      - postfix
      - zeo
      - postgres
    environment:
      ZOPE_MODE: "${ZOPE_MODE:-zeo_client}"
      TZ: "Europe/Copenhagen"
    entrypoint: >-
      ./bin/buildout plonesite:enabled=True install plonesite

  zeo:
    image: "${IMAGE:-eeacms/plone}"
    environment:
      ZOPE_MODE: "zeo"
      TZ: "Europe/Copenhagen"
    volumes:
      - zeo:/data
    command:
      - zeo

  postgres:
    image: eeacms/postgres:9.6-3.5
    environment:
      POSTGRES_DBNAME: "datafs zasync"
      POSTGRES_DBUSER: "zope"
      POSTGRES_DBPASS: "zope"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Europe/Bucharest"
    volumes:
    - postgres:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5.20
    command:
    - "-m"
    - "1024"
    environment:
      TZ: "Europe/Copenhagen"

  postfix:
    image: eeacms/postfix:2.10-3.3
    environment:
      MTP_HOST: "example.com"
      TZ: "Europe/Copenhagen"

volumes:
  zeo:
    driver: local
  postgres:
    driver: local
